version: '3.9'

services:
  backend:
    image: django_prod_backend
    build:
      context: ./backend
    restart: always
    volumes:
      - static-data:/vol/web

  frontend:
    image: react_prod_frontend
    build:
      context: ./frontend/client
      args:
        base_url: http://localhost     
    volumes:
      - react_build:/react_app/build
    command: npm run build 


  proxy:
    build:
      context: ./nginx
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - 80:8000
    volumes:
      # - static-data:/vol/static
      - react_build:/var/www/react

volumes:
  react_build:
  static-data: