version: '3.9'

services:
  backend:
    build:
      context: ./backend

    ports:
      - 8000:8000
    volumes:
      - ./backend/:/django_app
    command: python manage.py runserver 0.0.0.0:8000
  frontend:
    build:
      context: ./frontend/client
    volumes:
      - './frontend/client/:/react_app'
      -  '/react_app/node_modules'
    ports:
      - 3000:3000
    command:  npm start
