version: '3.9'

services:
  backend:
    image: django_prod_backend
    build:
      context: ./backend
    restart: always
    volumes:
      - static-data:/vol/web

  # frontend:
  #   image: react_frontend
  #   volumes:
  #     - react_build:/react/build


  proxy:
    build:
      context: ./nginx
    restart: always
    depends_on:
      - backend
    ports:
      - 80:8000
    volumes:
      - static-data:/vol/static

volumes:
  react_build:
  static-data: